services:
  qdrant:
    image: qdrant/qdrant
    container_name: qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./data:/qdrant/storage

  notebook:
    image: jupyter/scipy-notebook:latest
    container_name: notebook
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./datasets:/home/jovyan/datasets
    depends_on:
      - qdrant